services:
  mysql:
    image: mysql:8.0  
    container_name: fithub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lolipop1!  # Solo se necesita esta variable para el usuario root
      MYSQL_DATABASE: fithub_app  # Nombre de la base de datos
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  # Almacenar los datos en la máquina local
    networks:
      - fithub-network

networks:
  fithub-network:
    driver: bridge

volumes:
  mysql_data:
