version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fithub-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123a
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fithub-network

networks:
  fithub-network:
    driver: bridge

volumes:
  mongo_data:
